package TinyImageFormatGenerator

import collection.mutable.StringBuilder

case class WriteZigBlock(table: Seq[(String, GeneratorCode)]):
  val text = {
    var sb = StringBuilder()
    sb ++= "// Do Not Edit Autogenerated by tiny_image_format_generator\n\n"
    sb ++= "const TinyImageFormat = @import(\"tiny_image_format.zig\").Format;\n"

    genU32QueryFunc(sb, "WidthOfBlock", 0, { _.SizeAtBlockDim(BlockDim.Width) })
    genU32QueryFunc(sb, "HeightOfBlock", 0, { _.SizeAtBlockDim(BlockDim.Height) })
    genU32QueryFunc(sb, "DepthOfBlock", 0, { _.SizeAtBlockDim(BlockDim.Depth) })
    genU32QueryFunc(sb, "ByteSizeOfBlock", 0, { _.ByteSizeOfBlock })

    genPixelCountOfBlockFunc(sb)

    sb.result()

  }
  def genPixelCountOfBlockFunc(sb: StringBuilder) = {
    sb ++= "pub fn PixelCountOfBlock(fmt: TinyImageFormat) u32 {\n"
    sb ++= "    return WidthOfBlock(fmt) * HeightOfBlock(fmt) * DepthOfBlock(fmt);\n"
    sb ++= "}\n\n"
  }

  def genU32QueryFunc(sb: StringBuilder, name: String, default: Int, func: (GeneratorCode) => Int) =
    sb ++= s"pub fn $name(fmt: TinyImageFormat) u8 {\n"
    sb ++= "    switch(fmt) {\n"
    table.foreach(fmt => if func(fmt._2) != default then sb ++= f"        .${fmt._1} => return ${func(fmt._2)},\n")
    sb ++= s"        else => return $default,\n"
    sb ++= "    }\n"
    sb ++= "}\n\n"
